all: add graph-intel-api and testing and CI infrastructure
adevinta/graph-intel-api pull request #2
Opened 2022-12-01 17:22 UTC by jroimartin

This PR adds the command graph-intel-api as well as the testing and CI
infrastructure.

2022-12-03 15:38 UTC, manelmontilla requested changes

2022-12-03 15:38 UTC, manelmontilla commented on cmd/graph-intel-api/main.go
> +		log.Fatalf("error setting log level: %v", err)
s/error setting log level/graph-intel-api: error setting log level ?

2022-12-03 15:38 UTC, manelmontilla commented on intel/intel.go
> +			vid, err = api.resolveIP(ip)
It's not critical, but here a I think we should also break the execution of the `for` if the error returned by the `resolveIP` is not `nil` but different to `ErrNotFound`.  The reason is, in that case, we wouldn't have a controlled error, because the ip does not exists, but an uncontrolled one because unknown reasons.

2022-12-03 15:38 UTC, manelmontilla commented on gremlin/gremlin.go
> +// Connection creates a [Connection] with the provided configuration.
s/Connection/NewConnection

2022-12-03 15:38 UTC, manelmontilla commented on rest/rest.go
> +		}
I would log the `err` here before returning the 500, because if not, we will lose the info about the error.

2022-12-05 09:02 UTC, jroimartin commented on cmd/graph-intel-api/main.go
> +		log.Fatalf("error setting log level: %v", err)
Fixed.

2022-12-05 09:09 UTC, jroimartin commented on intel/intel.go
> +			vid, err = api.resolveIP(ip)
Good catch. It makes a lot of sense. Fixed.

2022-12-05 09:27 UTC, jroimartin commented on gremlin/gremlin.go
> +// Connection creates a [Connection] with the provided configuration.
I was surprised that the linter had not found this. So, I also fixed its configuration to detect this kind of issues. Actually, it detected another similar one and both are fixed now.

2022-12-05 09:30 UTC, jroimartin commented on rest/rest.go
> +		}
Fixed.

2022-12-05 09:55 UTC, manelmontilla approved these changes
LGTM

2022-12-05 10:01 UTC, merged